name: vvims
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_expandable_fab: ^2.0.0
  flutter_speed_dial: ^7.0.0
  camera: ^0.10.5+9
  provider: ^6.1.2
  connectivity_plus: ^6.0.2
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_mlkit_text_recognition: ^0.11.0
  change_app_package_name: ^1.1.0
  image_picker: ^1.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_app_check: ^0.1.5+2
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^9.8.0+1
  http: any
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.6
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/font/
    - assets/translations/

fonts:
    - family: Sk-Modernist
      fonts:
        - asset: assets/fonts/Sk-Modernist-Bold.otf
        - asset: assets/fonts/Sk-Modernist-Regular.otf
